id: A9E8CCE23
title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:33:44.386224
  last_modified_at: 2022-03-01 06:33:44.386232
